[package]
name = "monaddit-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
# Web framework
axum = { version = "0.8", features = ["ws", "macros"] }
tower = "0.5"
tower-http = { version = "0.6", features = ["cors", "trace"] }
hyper = { version = "1.7", features = ["full"] }

# Async runtime
tokio = { version = "1.47", features = ["full"] }

# Database
sqlx = { version = "0.8", features = [
    "runtime-tokio-rustls",
    "postgres",
    "chrono",
    "uuid",
    "migrate",
    "bigdecimal",
] }

bigdecimal = { version = "0.4", features = ["serde-json"] }

# In-memory cache and rate limiting
dashmap = "6.1"

# Blockchain interaction with Alloy
alloy = { version = "1.0", features = [
    "full",
    "node-bindings",
    "rpc-client-ws",
] }
alloy-primitives = "1.3"
alloy-sol-types = "1.3"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Environment and configuration
dotenv = "0.15"
config = "0.15"

# Logging and tracing
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }

# Crypto
sha3 = "0.10"
hex = "0.4"

# Time
chrono = { version = "0.4", features = ["serde"] }

# UUID
uuid = { version = "1.18", features = ["v4", "serde"] }

# Error handling
thiserror = "2.0"
anyhow = "1.0"

# HTTP client (for ML scoring service)
reqwest = { version = "0.12", features = ["json"] }

# Rate limiting
governor = "0.10"

# Auth/Security
jsonwebtoken = "9.3"
argon2 = "0.5"
rand = "0.9"

# Additional dependencies for missing items
futures-util = "0.3"

[dev-dependencies]
mockito = "1.7"
